//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public int bookID { get; set; }
        public string Title { get; set; }
        public string ATitle { get; set; }
        public Nullable<bool> status { get; set; }
        public string link { get; set; }
    }
}
