//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassLevel
    {
        public ClassLevel()
        {
            this.courses = new HashSet<course>();
            this.courses1 = new HashSet<course>();
            this.StudentLevels = new HashSet<StudentLevel>();
            this.tbl_Task = new HashSet<tbl_Task>();
        }
    
        public int id { get; set; }
        public string levelName { get; set; }
        public string levelAName { get; set; }
        public Nullable<int> fees { get; set; }
        public string scheduleFile { get; set; }
    
        public virtual ICollection<course> courses { get; set; }
        public virtual ICollection<course> courses1 { get; set; }
        public virtual ICollection<StudentLevel> StudentLevels { get; set; }
        public virtual ICollection<tbl_Task> tbl_Task { get; set; }
    }
}
