//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public course()
        {
            this.std_Crs = new HashSet<std_Crs>();
        }
    
        public int code { get; set; }
        public string crs_Name { get; set; }
        public string crs_AName { get; set; }
        public Nullable<int> levelID { get; set; }
        public Nullable<int> staffId { get; set; }
    
        public virtual ClassLevel ClassLevel { get; set; }
        public virtual ClassLevel ClassLevel1 { get; set; }
        public virtual ICollection<std_Crs> std_Crs { get; set; }
    }
}
