//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string ATitle { get; set; }
        public string Content { get; set; }
        public string AContent { get; set; }
        public Nullable<System.DateTime> NewsDate { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> adminId { get; set; }
    
        public virtual staff staff { get; set; }
    }
}
