//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLevel
    {
        public int id { get; set; }
        public Nullable<int> levelId { get; set; }
        public Nullable<int> stdId { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> paid { get; set; }
    
        public virtual ClassLevel ClassLevel { get; set; }
        public virtual student student { get; set; }
    }
}
