//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public student()
        {
            this.std_Crs = new HashSet<std_Crs>();
            this.StudentLevels = new HashSet<StudentLevel>();
            this.tbl_absence = new HashSet<tbl_absence>();
        }
    
        public int id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string Afname { get; set; }
        public string Alname { get; set; }
        public string email { get; set; }
        public string pass { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> FiredDate { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> levelId { get; set; }
        public byte[] Img { get; set; }
        public Nullable<int> classRoom { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> roleID { get; set; }
    
        public virtual parent parent { get; set; }
        public virtual ICollection<std_Crs> std_Crs { get; set; }
        public virtual tbl_role tbl_role { get; set; }
        public virtual ICollection<StudentLevel> StudentLevels { get; set; }
        public virtual ICollection<tbl_absence> tbl_absence { get; set; }
    }
}
